#!/bin/sh

#color
alias ls='ls --color=auto'
alias grep='grep --color=auto'

#duplicate
alias vim='/usr/local/bin/vim'

#ls
alias la='ls -a'
alias ll='ls -l'

#tmux
alias tmux='tmux -2' # run with 256 colors
alias trx='tmux resize -x'
alias try='tmux resize -y'

#git
alias gs='git status'
alias ga='git add'
alias gaa='git add -A'
alias gc='git commit -m'
alias gca='git commit -am'
alias gl='git log'

#ssh
alias irc='mosh irc'
alias pi='mosh pi'
alias spi='ssh pi'
alias nollkit='ssh nollkit'
alias styrit='ssh styrit'
alias backup='ssh pi \"backup\"'

#other
alias ql='qlmanage -p "$1" >& /dev/null'
alias sniff="sudo ngrep -d 'en1' -t '^(GET|POST) ' 'tcp and port 80'"
