syntax on

" Vundle
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Bundle 'gmarik/vundle'

Bundle 'Valloric/YouCompleteMe'
Bundle 'Raimondi/delimitMate'
Bundle 'scrooloose/nerdcommenter'
Bundle 'godlygeek/tabular'

Bundle 'altercation/vim-colors-solarized'

call vundle#end()
filetype plugin indent on

" Theme
set background=dark
let g:solarized_termtrans=0
let g:solarized_termcolors=256
let g:solarized_termtrans=1
colorscheme solarized
hi LineNr ctermfg=grey ctermbg=none
hi CursorLine ctermbg=236

" Settings
set autoindent
set backspace=2
set cursorline
set expandtab
set hlsearch
set ignorecase
set number
set ruler
set scrolloff=5
set shortmess=atI
set shiftwidth=4
set smartcase
set smartindent
set tabstop=4
set title

" Mappings
map \yy :.w !pbcopy<CR><CR>
map \p :r !pbpaste<CR>

" Commands
if !exists(":DiffOrig")
    command Diff vert new | set bt=nofile | r # | 0d_ | diffthis
              \ | wincmd p | diffthis
endif

" Autocommands
augroup reload_vimrc
    autocmd!
    autocmd BufWritePost $MYVIMRC source $MYVIMRC
augroup END
