#!/bin/sh

#color
alias ls='ls --color=auto'
alias grep='grep --color=auto'

#tmux
alias tmux='tmux -2' # run with 256 colors

#git
alias gs='git status'
alias ga='git add'
alias gaa='git add -A'
alias gc='git commit -m'
alias gca='git commit -am'
alias gl='git log'
alias gll='git pull'
alias gsh='git push'

#other
alias clearram='sync && echo 3 | sudo tee /proc/sys/vm/drop_caches > /dev/null'

alias weather='curl --silent wttr.in/gothenburg | head -n 17'
alias moreweather='curl --silent wttr.in/gothenburg'

alias feh='feh -.'

alias qutebrowser='qutebrowser --backend webengine'
alias spotify='spotify --force-device-scale-factor=1.7'

