#!/bin/sh

#color
alias ls='ls --color=auto'
alias grep='grep --color=auto'

#ls
alias la='ls -a'
alias ll='ls -l'

#tmux
alias tmux='tmux -2' # run with 256 colors
alias trx='tmux resize -x'
alias try='tmux resize -y'

#git
alias gs='git status'
alias ga='git add'
alias gaa='git add -A'
alias gc='git commit -m'
alias gca='git commit -am'
alias gl='git log'
alias gll='git pull'
alias gsh='git push'

#ssh
alias irc='mosh irc'
alias pi='mosh pi'
alias opi='ssh opi'
alias spi='ssh pi'

#other
alias externalmonitor='xrandr --output DisplayPort-1 --auto --right-of LVDS'
alias externalmonitoroff='xrandr --output DisplayPort-1 --off'
alias connceted='ping -q -w 1 -c 1 `ip r | grep default | cut -d " " -f 3` &> /dev/null'

alias feh='feh -.'
alias messenger='midori -e identify-as=MIDORI_IDENT_SAFARI -e show-navigationbar=false -e zoom-level=0.9 -a http://messenger.com'

alias startphone='sudo fastboot reboot'

