#!/bin/sh

#color
alias ls='ls --color=auto'
alias grep='grep --color=auto'

#ls
alias la='ls -a'
alias ll='ls -l'

#tmux
alias tmux='tmux -2' # run with 256 colors
alias trx='tmux resize -x'
alias try='tmux resize -y'

#git
alias gs='git status'
alias ga='git add'
alias gaa='git add -A'
alias gc='git commit -m'
alias gca='git commit -am'
alias gl='git log'
alias gll='git pull'
alias gsh='git push'

#ssh
alias irc='mosh irc'
alias pi='mosh pi'
alias opi='ssh opi'
alias spi='ssh pi'

#other
alias externalmonitor='xrandr --output DisplayPort-1 --auto --right-of LVDS'
alias externalmonitoroff='xrandr --output DisplayPort-1 --off'

alias weather='curl --silent wttr.in/gothenburg | head -n 17'
alias moreweather='curl --silent wttr.in/gothenburg'

alias feh='feh -.'

alias startphone='sudo fastboot reboot'

