#!/bin/sh

## Path
export DOTFILES=$HOME/.dotfiles

## Export variables for shell
export CLICOLOR=1

export EDITOR=vim
export VISUAL=vim
export BROWSER=qutebrowser

export LANG='en_US.UTF-8'
export LANGUAGE=$LANG

export PATH="$(ruby -e 'puts Gem.user_dir')/bin:$PATH"
export PATH=$PATH:~/.cabal/bin

## Make vim colors work in tmux
export TERM=xterm-256color
[ -n "$TMUX" ] && export TERM=screen-256color

source $DOTFILES/config/aliases
source liquidprompt

[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx

## To prevent the errorcode from the tmux line to show
true

