#!/bin/sh

# Caps as escape
setxkbmap se -option 'lv3:caps_switch'
xcape -e 'ISO_Level3_Shift=Escape'

# No dead keys
setxkbmap se -variant nodeadkeys

# Xmodmap
[[ -f ~/.Xmodmap ]] && xmodmap ~/.Xmodmap

# Xresources
[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources
[[ -f ~/.Xresources_rofi ]] && xrdb -merge -I$HOME ~/.Xresources_rofi
[[ -f ~/.Xresources_theme ]] && xrdb -merge -I$HOME ~/.Xresources_theme

# Autostart
unclutter -idle 2 &
nm-applet &
redshift 57.716015:11.871436 &
xcompmgr &
sxhkd &
toggleTrackpad &

# Autostart applications
# sleep 60 && syncdrive &
sleep 0.5 && qutebrowser & # To allow network to connect
urxvt &
urxvt &

# Start awesome
exec awesome

