#!/bin/sh

# Caps as escape
setxkbmap se -option 'lv3:caps_switch'
xcape -e 'ISO_Level3_Shift=Escape'
[[ -f ~/.Xmodmap ]] && xmodmap ~/.Xmodmap

# Xresources
[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources
[[ -f ~/.Xresources_rofi ]] && xrdb -merge -I$HOME ~/.Xresources_rofi
[[ -f ~/.Xresources_theme ]] && xrdb -merge -I$HOME ~/.Xresources_theme

# Autostart
unclutter -idle 2 &
nm-applet &
redshift 57.716015:11.871436 &
xcompmgr &
sxhkd &
toggleTrackpad &

# Autostart applications
# sleep 60 && syncdrive &
sleep 0.5 && qutebrowser & # To allow network to connect
urxvt &
urxvt &

# Startup sound
sleep 3 && mpg123 ~/.local/share/rascal/boot.mp3 &

# Start awesome
exec awesome

