## Paths
export DOTFILES=$HOME/.dotfiles

export PATH="$(ruby -e 'puts Gem.user_dir')/bin:$PATH"
export PATH=$PATH:~/.cabal/bin

## Completion
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
zstyle :compinstall filename '$HOME/.zshrc'

autoload -Uz compinit
compinit

fpath=(/usr/local/share/zsh-completions $fpath)

## Set options
setopt append_history
setopt auto_cd
setopt complete_aliases
setopt complete_in_word
setopt correct
setopt extended_glob
setopt no_match
setopt notify
setopt no_beep
bindkey -e

## History
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zhistory

## Export variables for shell
export CLICOLOR=1

export EDITOR=vim
export VISUAL=vim
export BROWSER=qutebrowser

export LANG='en_US.UTF-8'
export LANGUAGE=$LANG

## Make vim colors work in tmux
[ -n "$TMUX" ] && export TERM=screen-256color

## Aliases & keybindings
source $DOTFILES/config/aliases
source $DOTFILES/config/key-bindings.zsh

## LiquidPrompt
source liquidprompt

## Start X
if [[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] then
    exec startx
fi

